# Generated by Django 4.2 on 2023-04-28 01:34

from django.db import migrations, models
import django.db.models.deletion
import lnreader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=16, unique=True)),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Novel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=600)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "raws_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to original page the novel was published.",
                        verbose_name="Raws URL",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NovelCover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(upload_to=lnreader.models.novel_cover_path),
                ),
                (
                    "novel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lnreader.novel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NovelAltTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                (
                    "novel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lnreader.novel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChapterIllustration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "illustration",
                    models.ImageField(
                        upload_to=lnreader.models.chapter_illustration_path
                    ),
                ),
                ("order", models.IntegerField(unique=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lnreader.chapter",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chapter",
            name="novel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lnreader.novel"
            ),
        ),
    ]
